# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8b021ebdf013e5029869baebb35ff1e652913c71cdae8a1261884cb491bbe91c22f77a93cb1a9e901f7ff7be276b8265822c274feb643bd8d9685658437b2b

test:
  secret_key_base: 9dd340a62a157454c2e0a9cec6da8beda87bb23c486f74646394bb4af7ff40d70fe114c69c2a9cdc62b4925b65a7984903a001979e9b09d86935c9c71454ccbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
